server:
  port: 20000
  data:
    contactos: C:/ruta/archivos/contactos/
    events: C:/ruta/archivos/eventos/
    reservas: C:/ruta/archivos/reservas/
    out: C:/ruta/archivos/out/
    response: C:/ruta/archivos/response/
    equivalencia: C:/ruta/archivos/equivalencia/

whatsapp:
  api:
    base-url: https://graph.facebook.com/v21.0/414660938406899/messages
    token: EAAP998NXCyIBO3T3hI40TPCLJoETwvJlXOg6xXzdF8yc8guO5gYXIJeZBKpnfKXIKyeRBDOYITcwV80aRpWaSHG55Ejd4Eg1z3deSCha343xZAqEGqIe60Uu8MjzVIc6hiW5hLFemxCQnJH1X4b5U9yhdp5egxHRAW30LeRftv0TMNu66swdrxdt20zWKemkoMeVLxZCvEtsx46t7ltvQZAq
  cellNumber: 414660938406899
  templateName: menuprincipal
  templateVideo: https://res.cloudinary.com/drkaz7gd6/video/upload/v1732592503/swjcivtyxi43nll7walh.mp4