server:
  port: 20000
  data:
    contactos: C:/ruta/archivos/contactos/
    events: C:/ruta/archivos/eventos/
    reservas: C:/ruta/archivos/turnos/
    out: C:/ruta/archivos/out/
    response: C:/ruta/archivos/response/
    equivalencia: C:/ruta/archivos/equivalencia/
    tracking: C:/ruta/archivos/tracking/

whatsapp:
  api:
    base-url: https://graph.facebook.com/v21.0/414660938406899/messages
    token: EAAP998NXCyIBOwkQpGBJuEnYUnIp0CCZCbft0dBZCNr1kOLeFy35SCyEUXOEAnMkK3BZA3PnxRxQwZAWL6DKJS9qhkEF7s0xNWaOBxBWtSccRvZCyZCX7tATKgqiiZCa7ku8PWmoUfqhHjITAYAeYzVPz6V6Vgpqy0jAfJw1jBgNKSJCwBYLpYfsinftmj90rF0CqZBxlJlLJODWIHa8KiD5H9hVBgZDZD
  cellNumber: 414660938406899
  templateName: menuprincipal
  templateVideo: https://res.cloudinary.com/drkaz7gd6/video/upload/v1732592503/swjcivtyxi43nll7walh.mp4