server:
  port: 5000
  data:
    contactos: contactos/
    events: eventos/
    reservas: turnos/
    out: out/
    response: response/
    equivalencia: equivalencia/
    tracking: tracking/
    nota: nota/
    token: token

whatsapp:
  api:
    id: 1101260264846104
    secret: [secret]
    base-url: https://graph.facebook.com/v21.0/578846945306314/messages
    token-uri: https://graph.facebook.com/v16.0/oauth/access_token
    expiration-token-uri: https://graph.facebook.com/debug_token
    token: []
    challenge: 1386287589
  cellNumber: 5491138255605
  templateName: menuprincipal
  templateVideo: https://res.cloudinary.com/drkaz7gd6/video/upload/v1732592503/swjcivtyxi43nll7walh.mp4
aws:
  accessKeyId: [accessKeyId]
  secretAccessKey: [secretAccessKey]
  region: us-east-2
  bucket: beanstalk-apps-estudiogg
spring:
  cloud:
    aws:
      credentials:
        access-key: [accessKeyId]
        secret-key: [secretAccessKey]
      region: us-east-2
      sqs:
        enabled: true
        endpoint: https://sqs.us-east-2.amazonaws.com
      sns:
        enabled: false  
      stack:
        auto: false