server:
  port: 20000
  
whatsapp:
  api:
    base-url: https://graph.facebook.com/v20.0/414660938406899/messages
    token: EAAPplyLkMxgBOZB9PYzRgmZAG3p5stHjhtwaIBakoZBkcyQnBY58QnHDstxZAMtoHeyf4clcK1YIqoA8ZCGZC4SoAPAEyARFppDz4KazdiavM2nASV2fpzLK8hI5dygWszJFtiJrIU7oMIPwKnBclu4gzgIowZCYoylrQZB5Qy44o7Ul2wX1g7SkZCZC3bxSp0dIZAot2ZBRmOeGASV1ADbutc25B0WT
  cellNumber: 414660938406899


